### ISSUE TITLE
[Backends, Proto, Feature] Prototype for expression-based backend

### ISSUE THREAD

**Issue by madagra** [pasqal-io/qadence#141]
Use a symbolic expression library (e.g. `sympy`) to define the blocks and automatically enforce algebra rules. 

Make a small, self-contained, prototype in a separate branch for an expression-based system for our blocks. In particular, this should allow the following:
- right operator precedence
- possibility to simplify blocks according to some simple, but extensible rules

## Tasks for MVP
- [x] design proposals with clear requirements and implementation time estimate
- [x] draft implementation in a separate branch
  - [x] Block naming 
  - [x] Make `qubit_support` read-only
  - [x] Make `n_qubits` a class attribute
  - [x] Matrix and eigenvalues properties
- [x] Basic composition rules
  - [x] Can't create kron blocks with overlapping support
  - [x] Must be checked for correctness
- [x] Basic interplay with custom `Parameter` type
- [x] Define Pauli operators
- [x] Use Pauli operators as generators for rotation gates including parametrisation
- [x] Add `evaluate` function for parametrised matrices and eigenvalues
- [ ] Express HamEvo 
- [x] Compute basic expectation value on PyQ
- [ ] Express a set of predicates

## Further features (ETA: End of the year)
- [ ] Implement a `Projector`
- [ ] Make `qubit_support` great again

**Comment by Roland-djee** [comment]
Closing as moved elsewhere.
